# Generated by Django 4.1.3 on 2022-11-26 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mushrooms", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="slug",
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
